<?php
// Defineer variabelen voor evenement
$evenement_naam = $korteOmschrijving = $langeOmschrijving = $datumBegin = $datumEind = $prijs = "";
$maxDeelnemers = $extraTekst = $extraInschrijven = $annuleringsverzekering = $id = "";
$naamErr = $korteOmschrijvingErr = $langeOmschrijvingErr = $datumBeginErr = $datumEindErr = $prijsErr = "";
$maxDeelnemersErr = $extraTekstErr = $extraInschrijvenErr = $annuleringsverzekeringErr = $statusErr = "";
$aantal_beschikbaar = $aantalDagen = $aantalDagenErr = $extra_contact = $extra_deelnemer = "";
$evt = $sum = 0;
$status = 0;
?>