<?php
// Defineer variabelen voor opties
$optieNaam = $tekstVoor = $tekstAchter = $groep = $type = $prijs = $prijsPer = "";
$tooltipTekst = $evenementNaam = "";
$heeftHorLijn = "0";
$totaalAantal = null;
$perDeelnemer = "ja";
$label = $labelErr = $selectLabel = $selectLabelErr = "";
$isDefault = $isInternGebruik = $isKlantWijzigen = "nee";
$perDeelnemer = "ja";
$optieNaamErr = $tekstVoorErr = $tekstAchterErr = $groepErr = $typeErr = $prijsErr = $prijsPerErr = "";
$totaalAantalErr = $isDefaultErr = $perDeelnemerErr = "";
$statusErr = $isInternGebruikErr = $isKlantWijzigenErr = $tooltipTekstErr = $horizontaleLijnErr = "";
$status = $horizontaleLijn = $evt = 0;
$optieId = null;
