<?php
// Defineer variabelen voor persoon
$voornaam = $straat = $huisnummer = $postcode = $woonplaats = $landnaam = $email = $telefoonnummer =  "";
$achternaam = $tussenvoegsel = $geslacht = $geboortedatum = $huisnummer_toevoeging = "";
$voornaamErr = $straatErr = $huisnummerErr = $postcodeErr = $woonplaatsErr = $landnaamErr = $emailErr = $telefoonnummerErr =  "";
$achternaamErr = $tussenvoegselErr = $geslachtErr = $geboortedatumErr = $huisnummer_toevoegingErr = "";
